import fs from "fs/promises"
import path from "path"

import { stringify } from "yaml"

import { getDefaultIntentCatalog } from "./intentLoader"

interface BootstrapOptions {
	repair?: boolean
}

function orchestrationDir(cwd: string): string {
	return path.join(cwd, ".orchestration")
}

function sidecarPath(cwd: string, name: string): string {
	return path.join(orchestrationDir(cwd), name)
}

async function exists(filePath: string): Promise<boolean> {
	try {
		await fs.access(filePath)
		return true
	} catch {
		return false
	}
}

async function writeIfMissing(filePath: string, content: string): Promise<void> {
	if (!(await exists(filePath))) {
		await fs.writeFile(filePath, content, "utf-8")
	}
}

async function repairIntentCatalogIfRequested(cwd: string): Promise<void> {
	const target = sidecarPath(cwd, "active_intents.yaml")
	const raw = await fs.readFile(target, "utf-8")
	const backup = sidecarPath(cwd, `active_intents.yaml.bak.${Date.now()}`)
	await fs.writeFile(backup, raw, "utf-8")
	await fs.writeFile(target, stringify(getDefaultIntentCatalog()), "utf-8")
}

export async function bootstrapGovernanceFiles(cwd: string, options?: BootstrapOptions): Promise<void> {
	await fs.mkdir(orchestrationDir(cwd), { recursive: true })

	const intentsPath = sidecarPath(cwd, "active_intents.yaml")
	if (!(await exists(intentsPath))) {
		await fs.writeFile(intentsPath, stringify(getDefaultIntentCatalog()), "utf-8")
	} else if (options?.repair) {
		await repairIntentCatalogIfRequested(cwd)
	}

	await writeIfMissing(sidecarPath(cwd, "agent_trace.jsonl"), "")
	await writeIfMissing(
		sidecarPath(cwd, "intent_map.md"),
		[
			"# Intent Map",
			"",
			"Generated by governance bootstrap.",
			"",
			"## Intent -> Files",
			"",
			"- (run a governed task to populate mappings)",
			"",
		].join("\n"),
	)
	await writeIfMissing(
		sidecarPath(cwd, "CLAUDE.md"),
		["# CLAUDE", "", "Shared governance notes and recovery log.", "", "## Lessons Learned", ""].join("\n"),
	)
}
